trigger:
  branches:
    include:
    - master
    - ci/*
    - bug/*
    - feature/*

stages:
- template: /.azuredevops/templates/stages-build-version-number.yaml

- stage: Build
  dependsOn: Build_Version_Number

  jobs:
  - job: Build

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet build'
        command: 'build'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet test'
        command: test
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet pack'
        command: pack
        arguments: '--configuration $(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- template: /.azuredevops/templates/stages-sync-with-github.yaml
  parameters:
    repository: CopyWords.Parsers