trigger:
  branches:
    include:
    - master
    - ci/*
    - bug/*
    - feature/*

stages:
- stage: Build

  jobs:
  - job: Build

    steps:
    - bash: |
        echo "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId)"
      name: SetBuildName

    - task: PowerShell@2
      displayName: 'PowerShell Script - update version number in project files'
      inputs:
        targetType: filePath
        arguments: "-version '$(Build.BuildNumber)'"
        filePath: './.build/UpdateVersion.ps1'

    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet build'
        command: 'build'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet test'
        command: test
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        displayName: 'dotnet pack'
        command: pack
        arguments: '--configuration $(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- template: /.azuredevops/templates/stages-sync-with-github.yaml
  parameters:
    repository: CopyWords.Parsers